# Generated by Django 5.0.6 on 2024-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Course', models.CharField(max_length=30)),
                ('Confirm', models.CharField(max_length=30)),
                ('Bcode', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Mentor', models.CharField(max_length=30)),
                ('TimeSlot', models.CharField(max_length=30)),
            ],
        ),
    ]
