# Generated by Django 5.0.6 on 2024-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
