# Generated by Django 5.0.6 on 2024-07-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_students_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='TimeSlot',
        ),
    ]
