# Generated by Django 5.0.6 on 2024-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_students_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mentor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
